/**
 * @file @core/tokens/attrs.js
 * @description Centralized DOM attribute, role, and ARIA tokens.
 */

export const ATTRS = Object.freeze({
  EMPTY: '',
  TRUE: 'true',
  FALSE: 'false',
  NONE: 'none',
  BLOCK: 'block',
  AUTO: 'auto',
  DECODING_ASYNC: 'async',
  DECODING_SYNC: 'sync',
  LOADING_LAZY: 'lazy',
  LOADING_EAGER: 'eager',
  FETCH_PRIORITY_HIGH: 'high',
  FETCH_PRIORITY_LOW: 'low',
  TRIGGER_VIEWPORT: 'viewport',
  CAPTIONS: 'captions',
  ARIA_LABEL: 'aria-label',
  SMOOTH: 'smooth',
  INSTANT: 'instant',
  BUTTON: 'button',
  TEXT: 'text',
  CHECKBOX: 'checkbox',
  DEFAULT_LANG: 'en',
  SOURCE: 'source',
  THUMB: 'thumb',
  ALT: 'alt',
  WIDTH: 'width',
  HEIGHT: 'height',
  IS_VIDEO: 'is-video',
  CAN_EXPAND: 'can-expand',
  AUTO_PLAY: 'auto-play',
  CLASSES: 'classes',
  DELAY: 'delay',
  OFFSET: 'offset',
  TRIGGER: 'trigger',
  VISIBLE: 'visible',
  PROP: 'prop',
  SECTION: 'section',
  PX: 'px',
  VIDEO_MP4: 'video/mp4',
  SRC: 'src',
  HREF: 'href',
  TYPE: 'type',
  NAME: 'name',
  VALUE: 'value',
  OPEN: 'open',
  LABEL: 'label',
  TOUCH: 'touch',
  POINTER: 'pointer',
  DATA_INDEX: 'data-index',
  DATA_LANG: 'data-lang',
  CLASS_NAME: 'className',
  CLASS: 'class',
  ID: 'id',
  ROLE_DIALOG: 'dialog',
  ROLE_GROUP: 'group',
  ROLE_SWITCH: 'switch',
  ARIA_LABELLEDBY: 'aria-labelledby',
  ARIA_MODAL: 'aria-modal',
  TABINDEX: 'tabindex',
  DATA_IDX: 'data-idx',
  DATA_SEC: 'data-sec',
  DATA_COL: 'data-col',
  DATA_MIDX: 'data-midx',
  DATA_SIZE: 'data-size',
  DATA_ACTION: 'data-action',
  DATA_FIELD: 'data-field',
  DATA_THEME: 'data-theme',
  DATA_CONTENT: 'data-content',
  ARIA_HIDDEN: 'aria-hidden',
  HIDDEN: 'hidden',
})
