/**
 * @file @core/tokens/strings.js
 * @description Centralized primitive string tokens for 100% DRY compliance.
 */

export const STRINGS = Object.freeze({
  EMPTY: '',
  SLASH: '/',
  DOUBLE_SLASH: '//',
  COLON: ':',
  SEMICOLON: ';',
  COMMA: ',',
  DOT: '.',
  DASH: '-',
  UNDERSCORE: '_',
  EQUALS: '=',
  QUESTION: '?',
  AMPERSAND: '&',
  HASH: '#',
  PX: 'px',
  REM: 'rem',
  PERCENT: '%',
  PERCENT_100: '100%',
  ZERO: '0',
  ONE: '1',
  TRUE: 'true',
  FALSE: 'false',
  NONE: 'none',
  BLOCK: 'block',
  AUTO: 'auto',
  SMOOTH: 'smooth',
  INSTANT: 'instant',
  OPEN: 'open',
  UNDEFINED: 'undefined',
  FUNCTION: 'function',
  OBJECT: 'object',
  STRING: 'string',
  BOOLEAN: 'boolean',
  NUMBER: 'number',
  APPLE_VENDOR: 'Apple Computer, Inc.',
  CONTAINER_TYPE: 'container-type',
  INLINE_SIZE: 'inline-size',
  GESTURE_EVENT: 'GestureEvent',
  BR_TAG: '<br>',
  DELAY_30: '30',
  ONE_EM: '1em',
  VAR_RADIUS_FULL: 'var(--radius-full)',
  VAR_RADIUS_2XS: 'var(--radius-2xs)',
  MINUS_ONE: '-1',
  ABSOLUTE: 'absolute',
  RELATIVE: 'relative',
  HIDDEN: 'hidden',
  MOSAIC_CARD: 'mosaic_card',
  DELAY_8: '8',
  BATCH_LAYOUT: 'BATCH_LAYOUT',
  LOADING: 'loading',
})
