/**
 * @file @core/tokens/tags.js
 * @description Centralized DOM element and custom element tag name tokens.
 */

export const TAGS = Object.freeze({
  APP_ROOT: 'app-root',
  APP_NAV: 'app-nav',
  HOME_MOSAIC: 'home-mosaic',
  HOME_CAROUSEL: 'home-carousel',
  MEDIA_FIGURE: 'media-figure',
  MEDIA_EXPANDED: 'media-expanded',
  ABOUT_SECTION: 'about-section',
  AWARDS_MENTIONS: 'awards-mentions',
  CONTACT_SECTION: 'contact-section',
  INTERNAL_FOOTER: 'internal-footer',
  RELATED_MOSAIC: 'related-mosaic',
  LEGAL_FOOTER: 'legal-footer',
  COOKIE_BANNER: 'cookie-banner',
  LANG_DIALOG: 'lang-dialog',
  PREFERENCES_MODAL: 'preferences-modal',
  SKELETON_PLACEHOLDER: 'skeleton-placeholder',
  DRAW_TEXT: 'draw-text',
  VIEW_HOME: 'view-home',
  VIEW_PROJECT: 'view-project',
  VIEW_LEGAL: 'view-legal',
  VIEW_NOT_FOUND: 'view-not-found',
  STATS_HUD: 'stats-hud',
  FIGURE: 'figure',
  VIDEO: 'video',
  IMG: 'img',
  BUTTON: 'button',
  DIV: 'div',
  SPAN: 'span',
  P: 'p',
  A: 'a',
  INPUT: 'input',
  LABEL: 'label',
  BR: 'br',
  SVG: 'svg',
  SECTION: 'section',
  DIALOG: 'dialog',
  H1: 'h1',
  H2: 'h2',
  H3: 'h3',
  H4: 'h4',
  TEXTAREA: 'textarea',
  SELECT: 'select',
  OPTION: 'option',
  HEADER: 'header',
  FOOTER: 'footer',
  NAV: 'nav',
  STYLE: 'style',
})
