/**
 * @file @core/tokens/text.js
 * @description Centralized UI text labels used by public components and tests.
 */

export const TEXT = Object.freeze({
  SCROLL_UP: 'Back to Top',
  SCROLL_UP_ALT: 'Scroll up',
  CONTACT: 'Contact',
  ABOUT_ME: 'About Me',
  GET_IN_TOUCH: 'Get in Touch',
  CLICK_LABEL: 'Click',
  TAP_LABEL: 'Tap',
  SOME_MENTIONS: 'Some mentions',
  PREV_ITEM: 'Previous item',
  NEXT_ITEM: 'Next item',
  OF: 'of',
  FEATURED: 'Featured',
  CHECK_OUT: 'Check out',
  LANGUAGE: 'Language',
  CLOSE: 'Close',
  CLOSE_LANG_SELECTOR: 'Close language selector',
  LOADING: 'Loading',
  LOADING_DOTS: 'Loading...',
  SAVING: 'Saving...',
  SIGNING_IN: 'Signing in...',
  SIGN_IN_GOOGLE: 'Sign in with Google',
  LOGOUT: 'Logout',
  VIDEO_AUTOPLAY: 'Video autoplay',
  PERFORMANCE: 'Performance',
  MEMORY: 'Memory',
  NETWORK: 'Network',
  LATENCY: 'Latency',
  AI_ENGINE: 'AI Engine',
  ACCEPT: 'Accept',
  REFUSE: 'Refuse',
  TO_EXPAND: 'to expand',
  PERF_STATS_AND_CONTROLS: 'Performance stats and controls',
  VIDEO_CONTROLS: 'Video controls',
  ON: 'ON',
  OFF: 'OFF',
  FPS: 'FPS',
  CPU: 'CPU',
  NET: 'NET',
  LAT: 'LAT',
  REQ: 'REQ',
  MEM: 'MEM',
  GPU: 'GPU',
  KB_S: 'KB/s',
  MS: 'ms',
  MB: 'MB',
  DASH: '—',
})
