/**
 * @file three-tsl.js (mock)
 * @description Auto-mock for `three/tsl` — every exported node helper is a
 * chainable proxy so arbitrary node graphs (`texture(x).mul(y).add(z)`)
 * evaluate harmlessly.
 */
import { __chain as chain } from './three.js'

const NAMES = [
  'texture',
  'normalMap',
  'mix',
  'normalize',
  'cross',
  'cameraPosition',
  'positionWorld',
  'pow',
  'dot',
  'max',
  'vec2',
  'vec3',
  'vec4',
  'float',
  'min',
  'bumpMap',
  'smoothstep',
  'equirectUV',
  'positionLocal',
  'modelWorldMatrixInverse',
  'uniform',
  'length',
  'acos',
  'sub',
  'Fn',
  'atan2',
  'pass',
  'screenCoordinate',
  'screenSize',
  'time',
  'uv',
  'positionGeometry',
  'normalGeometry',
  'normalView',
  'positionView',
  'color',
  'oneMinus',
  'abs',
  'clamp',
  'floor',
  'fract',
  'sin',
  'cos',
  'step',
  'sign',
  'sqrt',
  'reflect',
  'refract',
  'distance',
  'exp',
  'screenUV',
  'viewportUV',
  'attribute',
  'varying',
  'instanceIndex',
]

const api = {}

NAMES.forEach((name) => {
  api[name] = chain()
})

// Fn must invoke the real node-builder callback so shader-graph math inside
// Fn(({ color, ... }) => …) bodies is actually exercised under tests.
api.Fn = (cb) => (args) => cb(args)

export const {
  texture,
  normalMap,
  mix,
  normalize,
  cross,
  cameraPosition,
  positionWorld,
  pow,
  dot,
  max,
  vec2,
  vec3,
  vec4,
  float,
  min,
  bumpMap,
  smoothstep,
  equirectUV,
  positionLocal,
  modelWorldMatrixInverse,
  uniform,
  length,
  acos,
  sub,
  Fn,
  atan2,
  pass,
  screenCoordinate,
  screenSize,
  time,
  uv,
  positionGeometry,
  normalGeometry,
  normalView,
  positionView,
  color,
  oneMinus,
  abs,
  clamp,
  floor,
  fract,
  sin,
  cos,
  step,
  sign,
  sqrt,
  reflect,
  refract,
  distance,
  exp,
  screenUV,
  viewportUV,
  attribute,
  varying,
  instanceIndex,
} = api
